import Head from "next/head";
import { BsFillMoonFill, BsFillSunFill } from "react-icons/bs";
import { useEffect, useState } from "react";
import { AiOutlineDownload } from "react-icons/ai";
import FirstPage from "./FirstPage";
import About from "./About";
import Projects from "./Projects";
import Banner from "./Banner";
import ContactMe from "./ContactMe";
import Footer from "./Footer";
import withSuspense from "../Hydration/withSuspense";
import { motion, useScroll, useSpring } from "framer-motion";

const Home = () => {
	//this progress can be passed to the children
	const { progress } = useScroll();
	const [initialProgress, setInitialProgress] = useState(0.5);
	//Here changes the progress while scrolling
	useEffect(() => {
		setInitialProgress(progress);
		console.log("scroll");
	}, [progress]);

	const [darkMode, setDarkMode] = useState(false);
	const { scrollYProgress } = useScroll();
	const scaleX = useSpring(scrollYProgress, {
		stiffness: 100,
		damping: 30,
		restDelta: 0.001,
	});

	return (
		<div className={darkMode ? "dark" : ""}>
			<Head>
				<title>Jordi's Portfolio</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="bg-white dark:bg-gray-900 transition ease-in delay-100 font-bold">
				<section className="min-h-screen">
					<nav className=" z-10 py-7 flex justify-around overflow-hidden fixed top-0 min-w-full bg-gray-400 bg-opacity-20 backdrop-blur-md dark:bg-gray-700 dark:bg-opacity-20">
						<motion.div
							style={{
								scaleX,
							}}
							className="origin-left h-1 fixed right-0 bottom-0 left-0 bg-teal-700  top-0"
						></motion.div>
						<h1 className="text-xl dark:text-white">
							codedByJordi
						</h1>
						<ul className="flex items-center">
							<li>
								{darkMode ? (
									<BsFillSunFill
										onClick={() =>
											setDarkMode(
												!darkMode
											)
										}
										className="cursor-pointer text-2xl text-yellow-300"
									/>
								) : (
									<BsFillMoonFill
										onClick={() =>
											setDarkMode(
												!darkMode
											)
										}
										className="cursor-pointer text-2xl text-gray-900"
									/>
								)}
							</li>
							<li>
								<a
									style={{
										cursor: "pointer",
									}}
									onClick={() =>
										alert(
											"Ups! this feature is not working yet, my bad! :/"
										)
									}
									className="bg-gradient-to-r from-cyan-500 to-cyan-300 hover:from-cyan-500 hover:to-cyan-400 transition-colors ease-in duration-150 text-white px-4 py-2 border-none rounded-md ml-8 flex items-center gap-2"
								>
									Resume
									<AiOutlineDownload className="text-2xl" />
								</a>
							</li>
						</ul>
					</nav>
					<FirstPage darkMode={darkMode} />
				</section>
				<section>
					<About />
				</section>
				<section>
					<a id="Banner" href="#Form">
						<Banner />
					</a>
				</section>
				<section>
					<Projects />
				</section>
				<section id="Form">
					<ContactMe />
				</section>
				<section>
					<Footer />
				</section>
			</main>
		</div>
	);
};
export default withSuspense(Home);
